default:
    @just --list

gen-bitfields:
    #!/bin/bash
    python3 ./testbenches/generate_bitfield.py > ./testbenches/include/tb_bitfields.h

sim-b name:
    make ./build/{{name}}.bsim
    ./build/{{name}}.bsim

build-v name:
    make ./build/verilog/{{name}}.v

build-sim-v name:
    make ./build/{{name}}.vsim

sim-v name:
    make ./build/{{name}}.vsim
    ./build/{{name}}.vsim

test-keymgr: (sim-v "mkSimpleIOCapKeyManager_Tb")

test-exposer-v1: (sim-v "mkSimpleIOCapExposerV1_Tb")
test-exposer-v2: (sim-v "mkSimpleIOCapExposerV2_Tb")
test-exposer-v3: (sim-v "mkSimpleIOCapExposerV3_Tb")