default:
    @just --list

sim-b name:
    make ./build/{{name}}.bsim
    ./build/{{name}}.bsim

build-v name:
    make ./build/{{name}}.vsim

sim-v name:
    make ./build/{{name}}.vsim
    ./build/{{name}}.vsim

test-keymgr: (sim-v "mkSimpleIOCapKeyManager_Tb")

test-exposer: (sim-v "mkSimpleIOCapExposer_Tb")